language: objective-c
osx_image: xcode9

script:
  - set -o pipefail
  - xcodebuild clean build -project UUMarqueeViewDemo.xcodeproj -scheme UUMarqueeViewDemo -sdk iphonesimulator -configuration Debug